######################################################################
# Automatically generated by qmake (3.0) ?? 5? 9 17:03:45 2016
######################################################################

TEMPLATE = app
TARGET = unicode
INCLUDEPATH += .

# Input
SOURCES += main.cpp
